import { readFileSync } from "node:fs";
import { join } from "node:path";

/** Read the immutable identifier generated by the current Next.js build. */
export function getApplicationBuildId(buildDirectory = join(process.cwd(), ".next")) {
  try {
    const buildId = readFileSync(join(buildDirectory, "BUILD_ID"), "utf8").trim();
    return buildId || null;
  } catch {
    return null;
  }
}
