import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { ClubAdminNav } from "@/components/club-admin-nav";
import { Badge, EmptyState, Input, Select, Notice } from "@/components/ui";

export type MemberRow = { membership_id: string; person_id: string; app_account_id: string | null; line_identity_id: string | null; oa_follower_id: string | null; display_name: string; phone: string | null; email: string | null; birth_date: string | null; membership_status: string; role_key: string; line_login_status: string; oa_status: string; created_at: string };
const membershipLabel: Record<string, string> = { invited: "受邀中", active: "啟用", suspended: "暫停", disabled: "停用", ended: "已結束" };

export default async function MembersPage({ params, searchParams }: { params: Promise<{ clubId: string }>; searchParams: Promise<{ q?: string; status?: string; success?: string }> }) {
  const { clubId } = await params; const query = await searchParams; const supabase = await createClient();
  const { data, error } = await supabase.rpc("list_club_members", { p_club_id: clubId, p_query: query.q || null, p_status: query.status || null });
  if (error) return <Notice tone="error">您沒有查看社員的權限。</Notice>; const members = (data ?? []) as MemberRow[];
  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">會員管理</p><h1>社員</h1><p>先由扶輪社建立已知資料，再邀請社員完成身份確認。</p></div><div className="form-actions"><a className="button button-secondary" href={`/api/v1/clubs/${clubId}/members/export`}>Excel 匯出</a><Link className="button" href={`/clubs/${clubId}/members/new`}>＋ 新增社員</Link></div></header><ClubAdminNav clubId={clubId}/>{query.success && <Notice tone="success">社員狀態已更新。</Notice>}<form className="inline-form"><Input name="q" defaultValue={query.q} placeholder="搜尋姓名、手機或 Email"/><Select name="status" defaultValue={query.status ?? ""}><option value="">全部狀態</option><option value="active">啟用</option><option value="invited">受邀中</option><option value="suspended">暫停</option><option value="disabled">停用</option></Select><button className="button" type="submit">搜尋</button></form>{members.length === 0 ? <EmptyState title="找不到社員" body="調整搜尋條件，或新增第一位社員。"/> : <div className="table-wrap"><table><thead><tr><th>社員</th><th>聯絡方式</th><th>社籍</th><th>LINE Login</th><th>LINE OA</th><th></th></tr></thead><tbody>{members.map(member => <tr key={member.membership_id}><td><strong>{member.display_name}</strong></td><td>{member.phone ?? member.email ?? "—"}</td><td><Badge tone={member.membership_status === "active" ? "success" : "warning"}>{membershipLabel[member.membership_status] ?? member.membership_status}</Badge></td><td><Badge tone={member.line_identity_id ? "success" : "neutral"}>{member.line_identity_id ? "已綁定" : "未綁定"}</Badge></td><td><Badge tone={member.oa_follower_id ? "success" : "neutral"}>{member.oa_follower_id ? "已加入" : "未加入"}</Badge></td><td><Link href={`/clubs/${clubId}/members/${member.membership_id}`}>管理 →</Link></td></tr>)}</tbody></table></div>}</div>;
}
