begin;

alter table public.people
  add column birth_date date,
  add column avatar_url text,
  add column profile_completed_at timestamptz;

alter table public.club_memberships
  drop constraint club_memberships_membership_status_check;
alter table public.club_memberships
  add constraint club_memberships_membership_status_check
  check (membership_status in ('invited', 'active', 'suspended', 'disabled', 'ended'));

create table public.permissions (
  permission_key text primary key check (permission_key ~ '^[a-z][a-z0-9_.]+$'),
  description_zh_hant text not null check (btrim(description_zh_hant) <> ''),
  created_at timestamptz not null default now()
);

create table public.role_definitions (
  role_key text primary key check (role_key in ('platform_admin', 'president', 'secretary', 'finance', 'member')),
  role_name_zh_hant text not null,
  role_scope text not null check (role_scope in ('platform', 'club')),
  is_system boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.role_permissions (
  role_key text not null references public.role_definitions(role_key) on delete restrict,
  permission_key text not null references public.permissions(permission_key) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (role_key, permission_key)
);

create table public.club_role_assignments (
  id uuid primary key default extensions.gen_random_uuid(),
  club_id uuid not null references public.clubs(id) on delete restrict,
  app_account_id uuid not null references public.app_accounts(id) on delete restrict,
  role_key text not null references public.role_definitions(role_key) on delete restrict,
  assignment_status text not null default 'active' check (assignment_status in ('active', 'revoked')),
  granted_by_app_account_id uuid references public.app_accounts(id) on delete restrict,
  granted_at timestamptz not null default now(),
  revoked_by_app_account_id uuid references public.app_accounts(id) on delete restrict,
  revoked_at timestamptz,
  revoke_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (assignment_status <> 'revoked' or revoked_at is not null)
);
create unique index club_role_assignments_one_active_role
  on public.club_role_assignments (club_id, app_account_id, role_key)
  where assignment_status = 'active';
create index club_role_assignments_account_idx on public.club_role_assignments (app_account_id, club_id);

create table public.member_invitations (
  id uuid primary key default extensions.gen_random_uuid(),
  club_id uuid not null references public.clubs(id) on delete restrict,
  person_id uuid not null references public.people(id) on delete restrict,
  membership_id uuid not null references public.club_memberships(id) on delete restrict,
  invitation_kind text not null default 'member_join' check (invitation_kind in ('member_join', 'line_rebind')),
  delivery_method text not null default 'link' check (delivery_method in ('line', 'email', 'qr', 'link')),
  token_hash text not null unique check (length(token_hash) = 64),
  token_prefix text not null check (length(token_prefix) = 8),
  invitation_status text not null default 'pending'
    check (invitation_status in ('pending', 'sent', 'accepted', 'expired', 'cancelled')),
  expires_at timestamptz not null default (now() + interval '14 days'),
  invited_by_app_account_id uuid not null references public.app_accounts(id) on delete restrict,
  accepted_by_app_account_id uuid references public.app_accounts(id) on delete restrict,
  sent_at timestamptz,
  accepted_at timestamptz,
  cancelled_at timestamptz,
  cancelled_by_app_account_id uuid references public.app_accounts(id) on delete restrict,
  idempotency_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (invitation_status <> 'accepted' or (accepted_at is not null and accepted_by_app_account_id is not null)),
  check (invitation_status <> 'cancelled' or cancelled_at is not null)
);
create unique index member_invitations_one_open_membership
  on public.member_invitations (membership_id)
  where invitation_status in ('pending', 'sent');
create index member_invitations_club_status_idx on public.member_invitations (club_id, invitation_status, created_at desc);

create table public.invitation_logs (
  id bigint generated by default as identity primary key,
  invitation_id uuid not null references public.member_invitations(id) on delete restrict,
  club_id uuid not null references public.clubs(id) on delete restrict,
  actor_app_account_id uuid references public.app_accounts(id) on delete restrict,
  event_key text not null check (event_key in ('created', 'sent', 'resent', 'opened', 'accepted', 'cancelled', 'expired', 'failed')),
  delivery_method text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index invitation_logs_invitation_idx on public.invitation_logs (invitation_id, created_at);

create table public.line_login_configs (
  id uuid primary key default extensions.gen_random_uuid(),
  config_name text not null default 'default',
  provider_mode text not null default 'mock' check (provider_mode in ('mock', 'line')),
  channel_id text,
  channel_secret_env_key text not null default 'LINE_LOGIN_CHANNEL_SECRET',
  callback_url text not null default 'http://localhost:3000/api/auth/line/callback',
  config_status text not null default 'active' check (config_status in ('active', 'disabled')),
  created_by_app_account_id uuid references public.app_accounts(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index line_login_configs_one_active on public.line_login_configs ((true)) where config_status = 'active';

create table public.line_oauth_states (
  id uuid primary key default extensions.gen_random_uuid(),
  state_hash text not null unique check (length(state_hash) = 64),
  nonce_hash text not null check (length(nonce_hash) = 64),
  invitation_token_hash text,
  return_path text not null default '/dashboard',
  device_fingerprint_hash text,
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.line_identities (
  id uuid primary key default extensions.gen_random_uuid(),
  person_id uuid not null references public.people(id) on delete restrict,
  app_account_id uuid not null references public.app_accounts(id) on delete restrict,
  provider_subject text not null,
  display_name text,
  picture_url text,
  email text,
  identity_status text not null default 'active' check (identity_status in ('active', 'unbound', 'blocked')),
  bound_at timestamptz not null default now(),
  last_login_at timestamptz,
  unbound_at timestamptz,
  unbound_by_app_account_id uuid references public.app_accounts(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index line_identities_one_active_subject
  on public.line_identities (provider_subject) where identity_status = 'active';
create unique index line_identities_one_active_account
  on public.line_identities (app_account_id) where identity_status = 'active';

create table public.login_history (
  id bigint generated by default as identity primary key,
  app_account_id uuid references public.app_accounts(id) on delete restrict,
  auth_user_id uuid references auth.users(id) on delete restrict,
  provider_key text not null check (provider_key in ('password', 'line', 'line_mock', 'invite')),
  outcome text not null check (outcome in ('success', 'failed', 'blocked')),
  ip_address inet,
  user_agent text,
  device_id uuid,
  failure_code text,
  created_at timestamptz not null default now()
);
create index login_history_account_created_idx on public.login_history (app_account_id, created_at desc);

create table public.user_devices (
  id uuid primary key default extensions.gen_random_uuid(),
  app_account_id uuid not null references public.app_accounts(id) on delete restrict,
  device_fingerprint_hash text not null,
  device_name text not null default '未知裝置',
  user_agent text,
  session_id uuid,
  trusted boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index user_devices_account_fingerprint on public.user_devices (app_account_id, device_fingerprint_hash);

create table public.notification_settings (
  app_account_id uuid primary key references public.app_accounts(id) on delete restrict,
  line_enabled boolean not null default true,
  email_enabled boolean not null default true,
  security_alerts boolean not null default true,
  club_announcements boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.privacy_settings (
  app_account_id uuid primary key references public.app_accounts(id) on delete restrict,
  show_email_to_club boolean not null default false,
  show_phone_to_club boolean not null default false,
  show_birthday_year boolean not null default false,
  analytics_consent boolean not null default false,
  updated_at timestamptz not null default now()
);

create table public.line_oa_accounts (
  id uuid primary key default extensions.gen_random_uuid(),
  club_id uuid not null references public.clubs(id) on delete restrict,
  display_name text not null,
  basic_id text,
  channel_id text,
  channel_secret_env_key text not null default 'LINE_OA_CHANNEL_SECRET',
  access_token_env_key text not null default 'LINE_OA_CHANNEL_ACCESS_TOKEN',
  webhook_secret_env_key text not null default 'LINE_OA_CHANNEL_SECRET',
  rich_menu_id text,
  account_status text not null default 'configured' check (account_status in ('configured', 'active', 'disabled')),
  created_by_app_account_id uuid references public.app_accounts(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index line_oa_accounts_one_active_club on public.line_oa_accounts (club_id) where account_status <> 'disabled';

create table public.line_oa_followers (
  id uuid primary key default extensions.gen_random_uuid(),
  line_oa_account_id uuid not null references public.line_oa_accounts(id) on delete restrict,
  club_id uuid not null references public.clubs(id) on delete restrict,
  person_id uuid references public.people(id) on delete restrict,
  app_account_id uuid references public.app_accounts(id) on delete restrict,
  oa_user_id text not null,
  follower_status text not null default 'following' check (follower_status in ('following', 'blocked', 'unpaired')),
  followed_at timestamptz not null default now(),
  paired_at timestamptz,
  unpaired_at timestamptz,
  updated_at timestamptz not null default now()
);
create unique index line_oa_followers_account_user on public.line_oa_followers (line_oa_account_id, oa_user_id);
create unique index line_oa_followers_one_active_person on public.line_oa_followers (line_oa_account_id, person_id) where follower_status = 'following' and person_id is not null;

create table public.line_push_logs (
  id uuid primary key default extensions.gen_random_uuid(),
  line_oa_account_id uuid not null references public.line_oa_accounts(id) on delete restrict,
  club_id uuid not null references public.clubs(id) on delete restrict,
  requested_by_app_account_id uuid references public.app_accounts(id) on delete restrict,
  push_kind text not null check (push_kind in ('broadcast', 'multicast', 'push', 'reply', 'rich_menu')),
  recipient_count integer not null default 0 check (recipient_count >= 0),
  payload_summary jsonb not null default '{}'::jsonb,
  delivery_status text not null default 'queued' check (delivery_status in ('queued', 'sent', 'failed', 'mocked')),
  provider_request_id text,
  failure_code text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.line_webhooks (
  id bigint generated by default as identity primary key,
  line_oa_account_id uuid not null references public.line_oa_accounts(id) on delete restrict,
  club_id uuid not null references public.clubs(id) on delete restrict,
  event_type text not null,
  provider_event_id text,
  signature_valid boolean not null,
  payload_hash text not null,
  processing_status text not null default 'received' check (processing_status in ('received', 'processed', 'ignored', 'failed')),
  failure_code text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);
create unique index line_webhooks_provider_event_unique on public.line_webhooks (line_oa_account_id, provider_event_id) where provider_event_id is not null;

insert into public.permissions (permission_key, description_zh_hant) values
  ('dashboard.read', '查看社級儀表板'),
  ('member.read', '查看社員'),
  ('member.manage', '新增、編輯與停用社員'),
  ('invitation.manage', '建立、重送與取消社員邀請'),
  ('identity.read', '查看登入身份、裝置與紀錄'),
  ('identity.unbind', '解除 LINE Login 綁定'),
  ('oa.read', '查看 LINE OA 狀態'),
  ('oa.manage', '設定 LINE OA、配對與推播'),
  ('role.manage', '管理社級角色'),
  ('audit.read', '查看稽核紀錄'),
  ('finance.read', '查看財務身份範圍'),
  ('profile.self', '管理自己的資料與偏好');

insert into public.role_definitions (role_key, role_name_zh_hant, role_scope) values
  ('platform_admin', '平台管理員', 'platform'),
  ('president', '社長', 'club'),
  ('secretary', '秘書', 'club'),
  ('finance', '財務', 'club'),
  ('member', '一般社員', 'club');

insert into public.role_permissions (role_key, permission_key)
select role_key, permission_key from (values
  ('platform_admin', 'dashboard.read'), ('platform_admin', 'member.read'), ('platform_admin', 'member.manage'),
  ('platform_admin', 'invitation.manage'), ('platform_admin', 'identity.read'), ('platform_admin', 'identity.unbind'),
  ('platform_admin', 'oa.read'), ('platform_admin', 'oa.manage'), ('platform_admin', 'role.manage'), ('platform_admin', 'audit.read'),
  ('president', 'dashboard.read'), ('president', 'member.read'), ('president', 'member.manage'),
  ('president', 'invitation.manage'), ('president', 'identity.read'), ('president', 'identity.unbind'),
  ('president', 'oa.read'), ('president', 'oa.manage'), ('president', 'role.manage'), ('president', 'audit.read'),
  ('secretary', 'dashboard.read'), ('secretary', 'member.read'), ('secretary', 'member.manage'),
  ('secretary', 'invitation.manage'), ('secretary', 'identity.read'), ('secretary', 'identity.unbind'),
  ('secretary', 'oa.read'), ('secretary', 'oa.manage'), ('secretary', 'audit.read'),
  ('finance', 'dashboard.read'), ('finance', 'member.read'), ('finance', 'finance.read'),
  ('member', 'dashboard.read'), ('member', 'profile.self')
) as grants(role_key, permission_key);

create trigger club_role_assignments_set_updated_at before update on public.club_role_assignments
for each row execute function public.set_updated_at();
create trigger member_invitations_set_updated_at before update on public.member_invitations
for each row execute function public.set_updated_at();
create trigger line_login_configs_set_updated_at before update on public.line_login_configs
for each row execute function public.set_updated_at();
create trigger line_identities_set_updated_at before update on public.line_identities
for each row execute function public.set_updated_at();
create trigger user_devices_set_updated_at before update on public.user_devices
for each row execute function public.set_updated_at();
create trigger line_oa_accounts_set_updated_at before update on public.line_oa_accounts
for each row execute function public.set_updated_at();
create trigger line_oa_followers_set_updated_at before update on public.line_oa_followers
for each row execute function public.set_updated_at();

alter table public.permissions enable row level security;
alter table public.role_definitions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.club_role_assignments enable row level security;
alter table public.member_invitations enable row level security;
alter table public.invitation_logs enable row level security;
alter table public.line_login_configs enable row level security;
alter table public.line_oauth_states enable row level security;
alter table public.line_identities enable row level security;
alter table public.login_history enable row level security;
alter table public.user_devices enable row level security;
alter table public.notification_settings enable row level security;
alter table public.privacy_settings enable row level security;
alter table public.line_oa_accounts enable row level security;
alter table public.line_oa_followers enable row level security;
alter table public.line_push_logs enable row level security;
alter table public.line_webhooks enable row level security;

revoke all on table public.permissions, public.role_definitions, public.role_permissions,
  public.club_role_assignments, public.member_invitations, public.invitation_logs,
  public.line_login_configs, public.line_oauth_states, public.line_identities,
  public.login_history, public.user_devices, public.notification_settings,
  public.privacy_settings, public.line_oa_accounts, public.line_oa_followers,
  public.line_push_logs, public.line_webhooks from anon, authenticated;

grant select, insert, update on table public.permissions, public.role_definitions, public.role_permissions,
  public.club_role_assignments, public.member_invitations, public.line_login_configs,
  public.line_oauth_states, public.line_identities, public.user_devices,
  public.notification_settings, public.privacy_settings, public.line_oa_accounts,
  public.line_oa_followers to service_role;
grant select, insert on table public.invitation_logs, public.login_history,
  public.line_push_logs, public.line_webhooks to service_role;
grant update on table public.line_webhooks to service_role;
grant usage, select on sequence public.invitation_logs_id_seq, public.login_history_id_seq,
  public.line_webhooks_id_seq to service_role;

commit;
