begin;

create table public.platform_feature_flag_audit (
  id bigint generated by default as identity primary key,
  feature_key text not null check (feature_key in (
    'role_context_v2',
    'role_shells_v2',
    'member_home_v2',
    'checkin_qr_v2',
    'checkin_gps_v2',
    'attendance_ui_v2',
    'announcements_v09'
  )),
  action_type text not null check (action_type in (
    'created', 'enabled', 'disabled', 'enabled_environments_changed', 'rollout_percentage_changed'
  )),
  before_configuration jsonb,
  after_configuration jsonb not null,
  actor_identifier_snapshot uuid not null,
  occurred_at timestamptz not null default now(),
  retention_class text not null default 'club_mutation_audit_3y'
    check (retention_class = 'club_mutation_audit_3y')
);

comment on table public.platform_feature_flag_audit is
  'Append-only feature-flag audit with an independent immutable actor UUID snapshot.';

create index platform_feature_flag_audit_retention_occurred_at_idx
  on public.platform_feature_flag_audit (retention_class, occurred_at, id);

alter table public.platform_feature_flag_audit enable row level security;

revoke all on table public.platform_feature_flag_audit from public, anon, authenticated;

create or replace function public.platform_feature_flag_configuration(p_flag public.platform_feature_flags)
returns jsonb
language sql
immutable
set search_path = pg_catalog, public
as $$
  select pg_catalog.jsonb_build_object(
    'feature_key', p_flag.feature_key,
    'enabled', p_flag.enabled,
    'enabled_environments', p_flag.enabled_environments,
    'rollout_percentage', p_flag.rollout_percentage
  )
$$;

create or replace function public.append_platform_feature_flag_audit()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  actor_id uuid := public.current_app_account_id();
  before_value jsonb;
  after_value jsonb;
begin
  if actor_id is null then
    raise exception using errcode = '42501', message = 'platform_feature_flag_actor_required';
  end if;

  if tg_op = 'INSERT' then
    insert into public.platform_feature_flag_audit (
      feature_key, action_type, before_configuration, after_configuration, actor_identifier_snapshot
    ) values (
      new.feature_key, 'created', null, public.platform_feature_flag_configuration(new), actor_id
    );
    return new;
  end if;

  before_value := public.platform_feature_flag_configuration(old);
  after_value := public.platform_feature_flag_configuration(new);
  if old.enabled is distinct from new.enabled then
    insert into public.platform_feature_flag_audit (
      feature_key, action_type, before_configuration, after_configuration, actor_identifier_snapshot
    ) values (
      new.feature_key,
      case when new.enabled then 'enabled' else 'disabled' end,
      before_value,
      after_value,
      actor_id
    );
  end if;
  if old.enabled_environments is distinct from new.enabled_environments then
    insert into public.platform_feature_flag_audit (
      feature_key, action_type, before_configuration, after_configuration, actor_identifier_snapshot
    ) values (
      new.feature_key, 'enabled_environments_changed', before_value, after_value, actor_id
    );
  end if;
  if old.rollout_percentage is distinct from new.rollout_percentage then
    insert into public.platform_feature_flag_audit (
      feature_key, action_type, before_configuration, after_configuration, actor_identifier_snapshot
    ) values (
      new.feature_key, 'rollout_percentage_changed', before_value, after_value, actor_id
    );
  end if;
  return new;
end;
$$;

create trigger platform_feature_flags_append_audit
after insert or update on public.platform_feature_flags
for each row execute function public.append_platform_feature_flag_audit();

create or replace function public.prevent_platform_feature_flag_audit_mutation()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
begin
  if tg_op = 'DELETE'
    and pg_catalog.current_setting('app.platform_retention_cleanup', true) = 'true' then
    return old;
  end if;
  raise exception using errcode = '55000', message = 'platform_feature_flag_audit_is_append_only';
end;
$$;

create trigger platform_feature_flag_audit_prevent_mutation
before update or delete on public.platform_feature_flag_audit
for each row execute function public.prevent_platform_feature_flag_audit_mutation();

create or replace function public.set_platform_feature_flag(
  p_feature_key text,
  p_enabled boolean,
  p_enabled_environments text[],
  p_rollout_percentage integer
)
returns table (
  feature_key text,
  enabled boolean,
  enabled_environments text[],
  rollout_percentage smallint,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
begin
  if not public.current_has_platform_role(array['superadmin', 'platform_admin']) then
    raise exception using errcode = '42501', message = 'platform_feature_flag_admin_required';
  end if;
  if p_feature_key not in (
    'role_context_v2', 'role_shells_v2', 'member_home_v2', 'checkin_qr_v2', 'checkin_gps_v2',
    'attendance_ui_v2', 'announcements_v09'
  ) or p_enabled is null or p_enabled_environments is null
    or p_rollout_percentage not between 0 and 100
    or not (p_enabled_environments <@ array['local', 'staging', 'production']::text[]) then
    raise exception using errcode = '22023', message = 'invalid_platform_feature_flag_input';
  end if;

  return query
  insert into public.platform_feature_flags as flag (
    feature_key, enabled, enabled_environments, rollout_percentage
  ) values (
    p_feature_key, p_enabled, p_enabled_environments, p_rollout_percentage::smallint
  )
  on conflict on constraint platform_feature_flags_pkey do update
    set enabled = excluded.enabled,
        enabled_environments = excluded.enabled_environments,
        rollout_percentage = excluded.rollout_percentage
  returning flag.feature_key, flag.enabled, flag.enabled_environments, flag.rollout_percentage, flag.updated_at;
end;
$$;

revoke all on function public.platform_feature_flag_configuration(public.platform_feature_flags) from public, anon, authenticated;
revoke all on function public.append_platform_feature_flag_audit() from public, anon, authenticated;
revoke all on function public.prevent_platform_feature_flag_audit_mutation() from public, anon, authenticated;
revoke all on function public.set_platform_feature_flag(text, boolean, text[], integer) from public, anon, authenticated;
grant execute on function public.set_platform_feature_flag(text, boolean, text[], integer) to authenticated;

commit;
