begin;

create table public.platform_login_security_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in (
    'login_success', 'login_failure', 'password_reset_requested'
  )),
  daily_subject text not null check (daily_subject ~ '^[0-9a-f]{64}$'),
  retention_class text not null default 'login_security_365d'
    check (retention_class = 'login_security_365d'),
  created_at timestamptz not null default now()
);

comment on table public.platform_login_security_events is
  'Reserved closed login-security retention sink. This PR adds no producer or browser interface.';

create index platform_login_security_events_retention_created_at_idx
  on public.platform_login_security_events (retention_class, created_at, id);

alter table public.platform_login_security_events enable row level security;

revoke all on table public.platform_login_security_events from public, anon, authenticated;
grant insert on table public.platform_login_security_events to service_role;

create or replace function public.cleanup_platform_retention(
  p_as_of timestamptz default now(),
  p_batch_size integer default 500
)
returns table (retention_class text, deleted_count bigint)
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  bounded_batch_size integer := least(greatest(coalesce(p_batch_size, 500), 1), 500);
  removed_count bigint;
begin
  if p_as_of is null then
    raise exception using errcode = '22023', message = 'retention_as_of_required';
  end if;

  if not pg_catalog.pg_try_advisory_xact_lock(
    pg_catalog.hashtextextended('platform_retention_cleanup', 0)
  ) then
    return query values
      ('product_checkin_90d'::text, 0::bigint),
      ('product_performance_90d'::text, 0::bigint),
      ('login_security_365d'::text, 0::bigint),
      ('club_mutation_audit_3y'::text, 0::bigint),
      ('operational_rate_limit_2d'::text, 0::bigint);
    return;
  end if;

  with deleted_rows as (
    delete from public.platform_product_telemetry
    where id in (
      select telemetry.id
      from public.platform_product_telemetry as telemetry
      where telemetry.retention_class = 'product_checkin_90d'
        and telemetry.created_at < p_as_of - interval '90 days'
      order by telemetry.created_at, telemetry.id
      limit bounded_batch_size
    )
    returning 1
  )
  select count(*) into removed_count from deleted_rows;
  return query select 'product_checkin_90d'::text, removed_count;

  with deleted_rows as (
    delete from public.platform_product_telemetry
    where id in (
      select telemetry.id
      from public.platform_product_telemetry as telemetry
      where telemetry.retention_class = 'product_performance_90d'
        and telemetry.created_at < p_as_of - interval '90 days'
      order by telemetry.created_at, telemetry.id
      limit bounded_batch_size
    )
    returning 1
  )
  select count(*) into removed_count from deleted_rows;
  return query select 'product_performance_90d'::text, removed_count;

  with deleted_rows as (
    delete from public.platform_login_security_events
    where id in (
      select security_event.id
      from public.platform_login_security_events as security_event
      where security_event.retention_class = 'login_security_365d'
        and security_event.created_at < p_as_of - interval '365 days'
      order by security_event.created_at, security_event.id
      limit bounded_batch_size
    )
    returning 1
  )
  select count(*) into removed_count from deleted_rows;
  return query select 'login_security_365d'::text, removed_count;

  perform pg_catalog.set_config('app.platform_retention_cleanup', 'true', true);
  with deleted_rows as (
    delete from public.platform_feature_flag_audit
    where id in (
      select audit.id
      from public.platform_feature_flag_audit as audit
      where audit.retention_class = 'club_mutation_audit_3y'
        and audit.occurred_at < p_as_of - interval '3 years'
      order by audit.occurred_at, audit.id
      limit bounded_batch_size
    )
    returning 1
  )
  select count(*) into removed_count from deleted_rows;
  return query select 'club_mutation_audit_3y'::text, removed_count;

  with deleted_rows as (
    delete from public.platform_product_telemetry_rate_limits
    where (daily_subject, event_name, window_started_at) in (
      select rate_limit.daily_subject, rate_limit.event_name, rate_limit.window_started_at
      from public.platform_product_telemetry_rate_limits as rate_limit
      where rate_limit.retention_class = 'operational_rate_limit_2d'
        and rate_limit.window_started_at < p_as_of - interval '2 days'
      order by rate_limit.window_started_at, rate_limit.daily_subject, rate_limit.event_name
      limit bounded_batch_size
    )
    returning 1
  )
  select count(*) into removed_count from deleted_rows;
  return query select 'operational_rate_limit_2d'::text, removed_count;
end;
$$;

revoke all on function public.cleanup_platform_retention(timestamptz, integer) from public, anon, authenticated;
grant execute on function public.cleanup_platform_retention(timestamptz, integer) to service_role;

commit;
