begin;

create table public.event_checkin_settings (
  event_id uuid primary key,
  club_id uuid not null,
  gps_enabled boolean not null default false,
  qr_enabled boolean not null default true,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  radius_meters integer,
  max_accuracy_meters integer,
  opens_at timestamptz not null,
  closes_at timestamptz not null,
  qr_rotation_seconds integer not null default 45,
  configured_by_app_account_id uuid not null references public.app_accounts(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_checkin_settings_event_club_fkey
    foreign key (event_id, club_id)
    references public.club_events (id, club_id)
    on delete restrict,
  constraint event_checkin_settings_method_check check (gps_enabled or qr_enabled),
  constraint event_checkin_settings_time_check check (closes_at > opens_at),
  constraint event_checkin_settings_rotation_check check (qr_rotation_seconds between 30 and 60),
  constraint event_checkin_settings_gps_check check (
    (
      gps_enabled
      and latitude between -90 and 90
      and longitude between -180 and 180
      and radius_meters between 50 and 2000
      and max_accuracy_meters between 20 and 500
    )
    or (
      not gps_enabled
      and latitude is null
      and longitude is null
      and radius_meters is null
      and max_accuracy_meters is null
    )
  ),
  constraint event_checkin_settings_id_club_unique unique (event_id, club_id)
);

create index event_checkin_settings_open_window_idx
  on public.event_checkin_settings (club_id, opens_at, closes_at);

alter table public.event_checkin_sessions
  alter column token_hash drop not null,
  alter column token_prefix drop not null;

create table public.event_checkin_qr_credentials (
  id uuid primary key default extensions.gen_random_uuid(),
  session_id uuid not null,
  club_id uuid not null,
  event_id uuid not null,
  token_hash text not null unique,
  token_prefix text not null,
  valid_from timestamptz not null default now(),
  expires_at timestamptz not null,
  invalidated_at timestamptz,
  issued_by_app_account_id uuid not null references public.app_accounts(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint event_checkin_qr_credentials_session_fkey
    foreign key (session_id, club_id, event_id)
    references public.event_checkin_sessions (id, club_id, event_id)
    on delete restrict,
  constraint event_checkin_qr_credentials_token_hash_check check (length(token_hash) = 64),
  constraint event_checkin_qr_credentials_token_prefix_check check (length(token_prefix) = 8),
  constraint event_checkin_qr_credentials_time_check check (expires_at > valid_from)
);

create index event_checkin_qr_credentials_session_idx
  on public.event_checkin_qr_credentials (session_id, expires_at desc);
create index event_checkin_qr_credentials_expiry_idx
  on public.event_checkin_qr_credentials (expires_at)
  where invalidated_at is null;

alter table public.event_attendances
  drop constraint event_attendances_method_check,
  drop constraint event_attendances_method_consistency,
  add column location_accuracy_meters numeric(10, 2),
  add column distance_meters numeric(12, 2),
  add constraint event_attendances_method_check
    check (checkin_method in ('qr', 'gps', 'manual')),
  add constraint event_attendances_method_consistency check (
    (
      checkin_method = 'qr'
      and checkin_session_id is not null
      and location_accuracy_meters is null
      and distance_meters is null
    )
    or (
      checkin_method = 'gps'
      and checkin_session_id is null
      and location_accuracy_meters is not null
      and distance_meters is not null
      and location_accuracy_meters >= 0
      and distance_meters >= 0
    )
    or (
      checkin_method = 'manual'
      and checkin_session_id is null
      and btrim(checkin_note) <> ''
      and location_accuracy_meters is null
      and distance_meters is null
    )
  );

create table public.event_checkin_attempts (
  id bigint generated by default as identity primary key,
  club_id uuid,
  event_id uuid,
  membership_id uuid,
  actor_app_account_id uuid references public.app_accounts(id) on delete restrict,
  method text not null,
  result_code text not null,
  location_accuracy_meters numeric(10, 2),
  distance_meters numeric(12, 2),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint event_checkin_attempts_event_club_fkey
    foreign key (event_id, club_id)
    references public.club_events (id, club_id)
    on delete restrict,
  constraint event_checkin_attempts_membership_club_fkey
    foreign key (membership_id, club_id)
    references public.club_memberships (id, club_id)
    on delete restrict,
  constraint event_checkin_attempts_target_check check (
    (event_id is null and club_id is null)
    or (event_id is not null and club_id is not null)
  ),
  constraint event_checkin_attempts_method_check check (method in ('qr', 'gps', 'manual')),
  constraint event_checkin_attempts_result_check check (btrim(result_code) <> ''),
  constraint event_checkin_attempts_accuracy_check check (
    location_accuracy_meters is null or location_accuracy_meters >= 0
  ),
  constraint event_checkin_attempts_distance_check check (
    distance_meters is null or distance_meters >= 0
  )
);

create index event_checkin_attempts_event_created_idx
  on public.event_checkin_attempts (club_id, event_id, created_at desc);
create index event_checkin_attempts_actor_created_idx
  on public.event_checkin_attempts (actor_app_account_id, created_at desc);

create or replace function public.current_checkin_membership_id(p_club_id uuid)
returns uuid
language sql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
  select membership.id
  from public.app_accounts as account
  join public.club_memberships as membership
    on membership.person_id = account.person_id
   and membership.club_id = p_club_id
   and membership.membership_status = 'active'
  join public.clubs as club
    on club.id = membership.club_id
   and club.club_status = 'active'
  where account.auth_user_id = auth.uid()
    and account.account_status = 'active'
  order by membership.created_at
  limit 1
$$;

create or replace function public.event_distance_meters(
  p_latitude_a numeric,
  p_longitude_a numeric,
  p_latitude_b numeric,
  p_longitude_b numeric
)
returns numeric
language sql
immutable
set search_path = pg_catalog
as $$
  select round((
    6371000 * acos(least(1::double precision, greatest(-1::double precision,
      sin(radians(p_latitude_a::double precision))
        * sin(radians(p_latitude_b::double precision))
      + cos(radians(p_latitude_a::double precision))
        * cos(radians(p_latitude_b::double precision))
        * cos(radians((p_longitude_b - p_longitude_a)::double precision))
    )))
  )::numeric, 2)
$$;

create or replace function public.record_event_checkin_attempt(
  p_club_id uuid,
  p_event_id uuid,
  p_membership_id uuid,
  p_actor_app_account_id uuid,
  p_method text,
  p_result_code text,
  p_location_accuracy_meters numeric default null,
  p_distance_meters numeric default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  insert into public.event_checkin_attempts (
    club_id, event_id, membership_id, actor_app_account_id, method, result_code,
    location_accuracy_meters, distance_meters, metadata
  ) values (
    p_club_id, p_event_id, p_membership_id, p_actor_app_account_id,
    p_method, p_result_code, p_location_accuracy_meters, p_distance_meters,
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function public.configure_event_checkin(
  p_club_id uuid,
  p_event_id uuid,
  p_gps_enabled boolean,
  p_qr_enabled boolean,
  p_latitude numeric,
  p_longitude numeric,
  p_radius_meters integer,
  p_max_accuracy_meters integer,
  p_opens_at timestamptz,
  p_closes_at timestamptz,
  p_qr_rotation_seconds integer default 45
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  actor_id uuid := public.current_app_account_id();
  target_event public.club_events;
  saved public.event_checkin_settings;
begin
  if actor_id is null or not public.current_can_manage_event_checkin(p_club_id) then
    raise exception using errcode = '42501', message = 'attendance_manage_required';
  end if;

  select * into target_event
  from public.club_events
  where id = p_event_id and club_id = p_club_id
  for share;
  if not found or target_event.event_status not in ('draft', 'published')
     or not target_event.counts_for_attendance then
    raise exception using errcode = '22023', message = 'event_not_checkin_eligible';
  end if;
  if not coalesce(p_gps_enabled, false) and not coalesce(p_qr_enabled, false) then
    raise exception using errcode = '22023', message = 'checkin_method_required';
  end if;
  if p_opens_at is null or p_closes_at is null or p_closes_at <= p_opens_at
     or p_opens_at < target_event.starts_at - interval '24 hours'
     or p_closes_at > target_event.ends_at + interval '24 hours'
     or p_qr_rotation_seconds is null
     or p_qr_rotation_seconds not between 30 and 60 then
    raise exception using errcode = '22023', message = 'invalid_checkin_window';
  end if;
  if coalesce(p_gps_enabled, false) and (
    p_latitude is null or p_latitude not between -90 and 90
    or p_longitude is null or p_longitude not between -180 and 180
    or p_radius_meters is null or p_radius_meters not between 50 and 2000
    or p_max_accuracy_meters is null or p_max_accuracy_meters not between 20 and 500
  ) then
    raise exception using errcode = '22023', message = 'invalid_checkin_location';
  end if;
  if exists (
    select 1
    from public.event_checkin_sessions
    where event_id = p_event_id
      and club_id = p_club_id
      and session_status = 'active'
  ) or exists (
    select 1
    from public.event_checkin_settings
    where event_id = p_event_id
      and club_id = p_club_id
      and now() between opens_at and closes_at
  ) then
    raise exception using errcode = '55000', message = 'checkin_session_active';
  end if;

  insert into public.event_checkin_settings (
    event_id, club_id, gps_enabled, qr_enabled, latitude, longitude,
    radius_meters, max_accuracy_meters, opens_at, closes_at,
    qr_rotation_seconds, configured_by_app_account_id
  ) values (
    p_event_id, p_club_id, coalesce(p_gps_enabled, false), coalesce(p_qr_enabled, false),
    case when p_gps_enabled then p_latitude else null end,
    case when p_gps_enabled then p_longitude else null end,
    case when p_gps_enabled then p_radius_meters else null end,
    case when p_gps_enabled then p_max_accuracy_meters else null end,
    p_opens_at, p_closes_at, p_qr_rotation_seconds, actor_id
  )
  on conflict (event_id) do update
  set gps_enabled = excluded.gps_enabled,
    qr_enabled = excluded.qr_enabled,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    radius_meters = excluded.radius_meters,
    max_accuracy_meters = excluded.max_accuracy_meters,
    opens_at = excluded.opens_at,
    closes_at = excluded.closes_at,
    qr_rotation_seconds = excluded.qr_rotation_seconds,
    configured_by_app_account_id = excluded.configured_by_app_account_id,
    updated_at = now()
  returning * into saved;

  insert into public.audit_logs (
    club_id, actor_app_account_id, action_key, subject_type, subject_id, metadata
  ) values (
    p_club_id, actor_id, 'attendance.settings_updated', 'club_event', p_event_id,
    jsonb_build_object(
      'gps_enabled', saved.gps_enabled,
      'qr_enabled', saved.qr_enabled,
      'radius_meters', saved.radius_meters,
      'max_accuracy_meters', saved.max_accuracy_meters,
      'opens_at', saved.opens_at,
      'closes_at', saved.closes_at,
      'qr_rotation_seconds', saved.qr_rotation_seconds
    )
  );

  return to_jsonb(saved) - 'latitude' - 'longitude';
end;
$$;

create or replace function public.start_event_checkin_session(
  p_club_id uuid,
  p_event_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  actor_id uuid := public.current_app_account_id();
  setting public.event_checkin_settings;
  target_event public.club_events;
  current_session public.event_checkin_sessions;
begin
  if actor_id is null or not public.current_can_manage_event_checkin(p_club_id) then
    raise exception using errcode = '42501', message = 'attendance_manage_required';
  end if;

  select event.* into target_event
  from public.club_events as event
  where event.id = p_event_id and event.club_id = p_club_id
  for update;
  select * into setting
  from public.event_checkin_settings
  where event_id = p_event_id and club_id = p_club_id;

  if target_event.id is null or setting.event_id is null or not setting.qr_enabled
     or target_event.event_status <> 'published'
     or not target_event.counts_for_attendance then
    raise exception using errcode = '22023', message = 'event_not_checkin_eligible';
  end if;
  if now() < setting.opens_at or now() > setting.closes_at then
    raise exception using errcode = '22023', message = 'checkin_window_closed';
  end if;

  select * into current_session
  from public.event_checkin_sessions
  where event_id = p_event_id and session_status = 'active'
  for update;

  if found and current_session.expires_at <= now() then
    update public.event_checkin_sessions
    set session_status = 'closed', closed_at = now(), close_reason = 'expired',
      closed_by_app_account_id = actor_id
    where id = current_session.id;
    current_session := null;
  elsif found then
    return jsonb_build_object(
      'session_id', current_session.id,
      'expires_at', current_session.expires_at,
      'idempotent', true
    );
  end if;

  insert into public.event_checkin_sessions (
    club_id, event_id, token_hash, token_prefix, opens_at, expires_at,
    created_by_app_account_id
  ) values (
    p_club_id, p_event_id, null, null, now(), setting.closes_at, actor_id
  ) returning * into current_session;

  insert into public.audit_logs (
    club_id, actor_app_account_id, action_key, subject_type, subject_id,
    metadata
  ) values (
    p_club_id, actor_id, 'attendance.session_opened', 'event_checkin_session',
    current_session.id,
    jsonb_build_object('event_id', p_event_id, 'expires_at', current_session.expires_at, 'version', 2)
  );

  return jsonb_build_object(
    'session_id', current_session.id,
    'expires_at', current_session.expires_at,
    'idempotent', false
  );
end;
$$;

create or replace function public.issue_event_checkin_qr(
  p_club_id uuid,
  p_event_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth, extensions
as $$
declare
  actor_id uuid := public.current_app_account_id();
  setting public.event_checkin_settings;
  current_session public.event_checkin_sessions;
  credential public.event_checkin_qr_credentials;
  raw_token text;
begin
  if actor_id is null or not public.current_can_manage_event_checkin(p_club_id) then
    raise exception using errcode = '42501', message = 'attendance_manage_required';
  end if;

  select * into setting
  from public.event_checkin_settings
  where event_id = p_event_id and club_id = p_club_id and qr_enabled;
  select * into current_session
  from public.event_checkin_sessions
  where event_id = p_event_id and club_id = p_club_id and session_status = 'active'
  for update;

  if setting.event_id is null or current_session.id is null
     or now() < setting.opens_at or now() > setting.closes_at
     or current_session.expires_at <= now() then
    raise exception using errcode = '22023', message = 'checkin_session_not_active';
  end if;

  update public.event_checkin_qr_credentials
  set invalidated_at = now()
  where session_id = current_session.id
    and invalidated_at is null
    and expires_at > now();

  raw_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.event_checkin_qr_credentials (
    session_id, club_id, event_id, token_hash, token_prefix,
    expires_at, issued_by_app_account_id
  ) values (
    current_session.id, p_club_id, p_event_id,
    encode(extensions.digest(raw_token, 'sha256'), 'hex'), left(raw_token, 8),
    least(
      now() + make_interval(secs => setting.qr_rotation_seconds),
      setting.closes_at,
      current_session.expires_at
    ),
    actor_id
  ) returning * into credential;

  return jsonb_build_object(
    'session_id', current_session.id,
    'token', raw_token,
    'expires_at', credential.expires_at,
    'rotation_seconds', setting.qr_rotation_seconds
  );
end;
$$;

create or replace function public.close_event_checkin(
  p_club_id uuid,
  p_event_id uuid,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  actor_id uuid := public.current_app_account_id();
  current_session public.event_checkin_sessions;
  reason text := btrim(coalesce(p_reason, ''));
  has_session boolean := false;
begin
  if actor_id is null or not public.current_can_manage_event_checkin(p_club_id) then
    raise exception using errcode = '42501', message = 'attendance_manage_required';
  end if;
  if reason = '' or char_length(reason) > 500 then
    raise exception using errcode = '22023', message = 'invalid_checkin_close_reason';
  end if;

  select * into current_session
  from public.event_checkin_sessions
  where event_id = p_event_id and club_id = p_club_id and session_status = 'active'
  for update;
  has_session := found;

  if not exists (
    select 1 from public.event_checkin_settings
    where event_id = p_event_id and club_id = p_club_id
  ) then
    raise exception using errcode = 'P0002', message = 'checkin_settings_not_available';
  end if;

  if has_session then
    update public.event_checkin_qr_credentials
    set invalidated_at = coalesce(invalidated_at, now())
    where session_id = current_session.id and invalidated_at is null;

    update public.event_checkin_sessions
    set session_status = 'closed', closed_at = now(), close_reason = reason,
      closed_by_app_account_id = actor_id
    where id = current_session.id;
  end if;

  update public.event_checkin_settings
  set closes_at = least(closes_at, now()), updated_at = now(),
    configured_by_app_account_id = actor_id
  where event_id = p_event_id and club_id = p_club_id;

  insert into public.audit_logs (
    club_id, actor_app_account_id, action_key, subject_type, subject_id,
    metadata
  ) values (
    p_club_id, actor_id,
    case when has_session then 'attendance.session_closed' else 'attendance.checkin_closed' end,
    case when has_session then 'event_checkin_session' else 'club_event' end,
    case when has_session then current_session.id else p_event_id end,
    jsonb_build_object('event_id', p_event_id, 'reason', reason, 'version', 2)
  );
end;
$$;

create or replace function public.preview_event_qr_checkin(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth, extensions
as $$
declare
  actor_id uuid := public.current_app_account_id();
  credential public.event_checkin_qr_credentials;
  current_session public.event_checkin_sessions;
  target_event public.club_events;
  setting public.event_checkin_settings;
  actor_membership_id uuid;
  recent_attempts integer;
begin
  if actor_id is null then
    raise exception using errcode = '42501', message = 'active_account_required';
  end if;
  select count(*)::integer into recent_attempts
  from public.event_checkin_attempts
  where actor_app_account_id = actor_id
    and created_at > now() - interval '1 minute';
  if recent_attempts >= 20 then
    perform public.record_event_checkin_attempt(
      null, null, null, actor_id, 'qr', 'rate_limited'
    );
    return jsonb_build_object('status', 'rate_limited');
  end if;

  if p_token is null or p_token !~ '^[0-9a-f]{64}$' then
    perform public.record_event_checkin_attempt(
      null, null, null, actor_id, 'qr', 'credential_invalid'
    );
    return jsonb_build_object('status', 'credential_invalid');
  end if;

  select * into credential
  from public.event_checkin_qr_credentials
  where token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex');
  if not found then
    perform public.record_event_checkin_attempt(
      null, null, null, actor_id, 'qr', 'credential_invalid'
    );
    return jsonb_build_object('status', 'credential_invalid');
  end if;

  actor_membership_id := public.current_checkin_membership_id(credential.club_id);
  if actor_membership_id is null then
    perform public.record_event_checkin_attempt(
      credential.club_id, credential.event_id, null, actor_id, 'qr', 'not_eligible'
    );
    return jsonb_build_object('status', 'not_eligible');
  end if;

  select * into current_session
  from public.event_checkin_sessions
  where id = credential.session_id;
  select * into setting
  from public.event_checkin_settings
  where event_id = credential.event_id and club_id = credential.club_id;
  select * into target_event
  from public.club_events
  where id = credential.event_id and club_id = credential.club_id;

  if credential.invalidated_at is not null or credential.expires_at <= now() then
    perform public.record_event_checkin_attempt(
      credential.club_id, credential.event_id, actor_membership_id, actor_id, 'qr', 'credential_expired'
    );
    return jsonb_build_object('status', 'credential_expired');
  end if;
  if current_session.id is null or current_session.session_status <> 'active'
     or current_session.expires_at <= now() then
    perform public.record_event_checkin_attempt(
      credential.club_id, credential.event_id, actor_membership_id, actor_id, 'qr', 'session_closed'
    );
    return jsonb_build_object('status', 'session_closed');
  end if;
  if target_event.id is null or setting.event_id is null or not setting.qr_enabled
     or now() < setting.opens_at or now() > setting.closes_at
     or target_event.event_status <> 'published'
     or not target_event.counts_for_attendance then
    perform public.record_event_checkin_attempt(
      credential.club_id, credential.event_id, actor_membership_id, actor_id, 'qr', 'window_closed'
    );
    return jsonb_build_object('status', 'window_closed');
  end if;

  return jsonb_build_object(
    'status', 'ready',
    'event_id', target_event.id,
    'title', target_event.title,
    'location', target_event.location,
    'starts_at', target_event.starts_at,
    'ends_at', target_event.ends_at,
    'credential_expires_at', credential.expires_at
  );
end;
$$;

create or replace function public.confirm_event_qr_checkin(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth, extensions
as $$
declare
  actor_id uuid := public.current_app_account_id();
  preview jsonb;
  credential public.event_checkin_qr_credentials;
  current_session public.event_checkin_sessions;
  target_event public.club_events;
  actor_membership_id uuid;
  existing_attendance public.event_attendances;
  created_attendance public.event_attendances;
begin
  preview := public.preview_event_qr_checkin(p_token);
  if preview->>'status' <> 'ready' then return preview; end if;

  select * into credential
  from public.event_checkin_qr_credentials
  where token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
  for update;
  select * into current_session
  from public.event_checkin_sessions
  where id = credential.session_id
  for share;
  select * into target_event
  from public.club_events
  where id = credential.event_id and club_id = credential.club_id
  for share;
  actor_membership_id := public.current_checkin_membership_id(credential.club_id);

  if credential.invalidated_at is not null or credential.expires_at <= now()
     or current_session.session_status <> 'active' or current_session.expires_at <= now() then
    perform public.record_event_checkin_attempt(
      credential.club_id, credential.event_id, actor_membership_id, actor_id, 'qr', 'credential_expired'
    );
    return jsonb_build_object('status', 'credential_expired');
  end if;
  if actor_membership_id is null
     or target_event.id is null
     or target_event.event_status <> 'published'
     or not target_event.counts_for_attendance
     or not exists (
       select 1
       from public.event_checkin_settings as setting
       where setting.event_id = credential.event_id
         and setting.club_id = credential.club_id
         and setting.qr_enabled
         and now() between setting.opens_at and setting.closes_at
     ) then
    perform public.record_event_checkin_attempt(
      credential.club_id, credential.event_id, actor_membership_id, actor_id, 'qr', 'window_closed'
    );
    return jsonb_build_object('status', 'window_closed');
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(target_event.id::text || ':' || actor_membership_id::text, 0)
  );

  select * into existing_attendance
  from public.event_attendances
  where event_id = target_event.id
    and membership_id = actor_membership_id
    and attendance_status = 'active';
  if found then
    perform public.record_event_checkin_attempt(
      credential.club_id, credential.event_id, actor_membership_id, actor_id, 'qr', 'already_checked_in'
    );
    return jsonb_build_object(
      'status', 'already_checked_in',
      'attendance_id', existing_attendance.id,
      'event_id', target_event.id,
      'title', target_event.title,
      'checked_in_at', existing_attendance.checked_in_at,
      'idempotent', true
    );
  end if;

  insert into public.event_attendances (
    club_id, event_id, membership_id, checkin_session_id, checkin_method,
    checked_in_by_app_account_id, checkin_note
  ) values (
    credential.club_id, credential.event_id, actor_membership_id, current_session.id,
    'qr', actor_id, ''
  ) returning * into created_attendance;

  perform public.record_event_checkin_attempt(
    credential.club_id, credential.event_id, actor_membership_id, actor_id, 'qr', 'success'
  );
  insert into public.audit_logs (
    club_id, actor_app_account_id, action_key, subject_type, subject_id, metadata
  ) values (
    credential.club_id, actor_id, 'attendance.self_checked_in', 'event_attendance',
    created_attendance.id,
    jsonb_build_object(
      'event_id', target_event.id,
      'membership_id', actor_membership_id,
      'session_id', current_session.id,
      'method', 'qr'
    )
  );

  return jsonb_build_object(
    'status', 'success',
    'attendance_id', created_attendance.id,
    'event_id', target_event.id,
    'title', target_event.title,
    'checked_in_at', created_attendance.checked_in_at,
    'idempotent', false
  );
end;
$$;

create or replace function public.check_in_by_gps(
  p_event_id uuid,
  p_latitude numeric,
  p_longitude numeric,
  p_accuracy_meters numeric
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  actor_id uuid := public.current_app_account_id();
  target_event public.club_events;
  setting public.event_checkin_settings;
  actor_membership_id uuid;
  measured_distance numeric;
  existing_attendance public.event_attendances;
  created_attendance public.event_attendances;
begin
  if actor_id is null then
    raise exception using errcode = '42501', message = 'active_account_required';
  end if;

  select event.* into target_event
  from public.club_events as event
  where event.id = p_event_id;
  if not found then return jsonb_build_object('status', 'not_eligible'); end if;
  select * into setting
  from public.event_checkin_settings
  where event_id = target_event.id and club_id = target_event.club_id;
  actor_membership_id := public.current_checkin_membership_id(target_event.club_id);

  if actor_membership_id is null or setting.event_id is null or not setting.gps_enabled
     or target_event.event_status <> 'published' or not target_event.counts_for_attendance then
    perform public.record_event_checkin_attempt(
      target_event.club_id, target_event.id, actor_membership_id, actor_id, 'gps', 'not_eligible'
    );
    return jsonb_build_object('status', 'not_eligible');
  end if;
  if now() < setting.opens_at or now() > setting.closes_at then
    perform public.record_event_checkin_attempt(
      target_event.club_id, target_event.id, actor_membership_id, actor_id, 'gps', 'window_closed'
    );
    return jsonb_build_object('status', 'window_closed');
  end if;
  if p_latitude is null or p_latitude not between -90 and 90
     or p_longitude is null or p_longitude not between -180 and 180
     or p_accuracy_meters is null or p_accuracy_meters < 0 or p_accuracy_meters > 10000 then
    perform public.record_event_checkin_attempt(
      target_event.club_id, target_event.id, actor_membership_id, actor_id, 'gps', 'location_invalid'
    );
    return jsonb_build_object('status', 'location_invalid');
  end if;

  measured_distance := public.event_distance_meters(
    setting.latitude, setting.longitude, p_latitude, p_longitude
  );
  if p_accuracy_meters > setting.max_accuracy_meters then
    perform public.record_event_checkin_attempt(
      target_event.club_id, target_event.id, actor_membership_id, actor_id, 'gps',
      'accuracy_insufficient', p_accuracy_meters, measured_distance
    );
    return jsonb_build_object(
      'status', 'accuracy_insufficient',
      'accuracy_meters', round(p_accuracy_meters, 2),
      'required_accuracy_meters', setting.max_accuracy_meters
    );
  end if;
  if measured_distance > setting.radius_meters then
    perform public.record_event_checkin_attempt(
      target_event.club_id, target_event.id, actor_membership_id, actor_id, 'gps',
      'outside_radius', p_accuracy_meters, measured_distance
    );
    return jsonb_build_object(
      'status', 'outside_radius',
      'distance_meters', measured_distance,
      'radius_meters', setting.radius_meters
    );
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(target_event.id::text || ':' || actor_membership_id::text, 0)
  );
  select * into existing_attendance
  from public.event_attendances
  where event_id = target_event.id
    and membership_id = actor_membership_id
    and attendance_status = 'active';
  if found then
    perform public.record_event_checkin_attempt(
      target_event.club_id, target_event.id, actor_membership_id, actor_id, 'gps',
      'already_checked_in', p_accuracy_meters, measured_distance
    );
    return jsonb_build_object(
      'status', 'already_checked_in',
      'attendance_id', existing_attendance.id,
      'event_id', target_event.id,
      'title', target_event.title,
      'checked_in_at', existing_attendance.checked_in_at,
      'idempotent', true
    );
  end if;

  insert into public.event_attendances (
    club_id, event_id, membership_id, checkin_method,
    checked_in_by_app_account_id, checkin_note,
    location_accuracy_meters, distance_meters
  ) values (
    target_event.club_id, target_event.id, actor_membership_id, 'gps', actor_id, '',
    round(p_accuracy_meters, 2), measured_distance
  ) returning * into created_attendance;

  perform public.record_event_checkin_attempt(
    target_event.club_id, target_event.id, actor_membership_id, actor_id, 'gps',
    'success', p_accuracy_meters, measured_distance
  );
  insert into public.audit_logs (
    club_id, actor_app_account_id, action_key, subject_type, subject_id, metadata
  ) values (
    target_event.club_id, actor_id, 'attendance.self_checked_in', 'event_attendance',
    created_attendance.id,
    jsonb_build_object(
      'event_id', target_event.id,
      'membership_id', actor_membership_id,
      'method', 'gps',
      'accuracy_meters', round(p_accuracy_meters, 2),
      'distance_meters', measured_distance
    )
  );

  return jsonb_build_object(
    'status', 'success',
    'attendance_id', created_attendance.id,
    'event_id', target_event.id,
    'title', target_event.title,
    'checked_in_at', created_attendance.checked_in_at,
    'distance_meters', measured_distance,
    'idempotent', false
  );
end;
$$;

create or replace function public.manual_check_in_event(
  p_club_id uuid,
  p_event_id uuid,
  p_membership_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  actor_id uuid := public.current_app_account_id();
  target_event public.club_events;
  setting public.event_checkin_settings;
  target_membership public.club_memberships;
  existing_attendance public.event_attendances;
  created_attendance public.event_attendances;
  reason text := btrim(coalesce(p_reason, ''));
begin
  if actor_id is null or not public.current_can_manage_event_checkin(p_club_id) then
    raise exception using errcode = '42501', message = 'attendance_manage_required';
  end if;
  if reason = '' or char_length(reason) > 500 then
    raise exception using errcode = '22023', message = 'manual_checkin_reason_required';
  end if;

  select * into target_event
  from public.club_events
  where id = p_event_id and club_id = p_club_id
  for share;
  select * into setting
  from public.event_checkin_settings
  where event_id = p_event_id and club_id = p_club_id;
  select * into target_membership
  from public.club_memberships
  where id = p_membership_id and club_id = p_club_id and membership_status = 'active'
  for share;

  if target_event.id is null or setting.event_id is null
     or target_event.event_status <> 'published'
     or not target_event.counts_for_attendance
     or target_membership.id is null then
    perform public.record_event_checkin_attempt(
      p_club_id, p_event_id, p_membership_id, actor_id, 'manual', 'not_eligible'
    );
    return jsonb_build_object('status', 'not_eligible');
  end if;
  if now() < setting.opens_at or now() > setting.closes_at then
    perform public.record_event_checkin_attempt(
      p_club_id, p_event_id, p_membership_id, actor_id, 'manual', 'window_closed'
    );
    return jsonb_build_object('status', 'window_closed');
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(target_event.id::text || ':' || target_membership.id::text, 0)
  );
  select * into existing_attendance
  from public.event_attendances
  where event_id = target_event.id
    and membership_id = target_membership.id
    and attendance_status = 'active';
  if found then
    perform public.record_event_checkin_attempt(
      p_club_id, p_event_id, p_membership_id, actor_id, 'manual', 'already_checked_in'
    );
    return jsonb_build_object(
      'status', 'already_checked_in',
      'attendance_id', existing_attendance.id,
      'event_id', existing_attendance.event_id,
      'checked_in_at', existing_attendance.checked_in_at,
      'idempotent', true
    );
  end if;

  insert into public.event_attendances (
    club_id, event_id, membership_id, checkin_method,
    checked_in_by_app_account_id, checkin_note
  ) values (
    p_club_id, p_event_id, p_membership_id, 'manual', actor_id, reason
  ) returning * into created_attendance;

  perform public.record_event_checkin_attempt(
    p_club_id, p_event_id, p_membership_id, actor_id, 'manual', 'success',
    null, null, jsonb_build_object('reason', reason)
  );
  insert into public.audit_logs (
    club_id, actor_app_account_id, action_key, subject_type, subject_id, metadata
  ) values (
    p_club_id, actor_id, 'attendance.manual_checked_in', 'event_attendance',
    created_attendance.id,
    jsonb_build_object('event_id', p_event_id, 'membership_id', p_membership_id, 'reason', reason)
  );

  return jsonb_build_object(
    'status', 'success',
    'attendance_id', created_attendance.id,
    'event_id', created_attendance.event_id,
    'checked_in_at', created_attendance.checked_in_at,
    'idempotent', false
  );
end;
$$;

create or replace function public.get_my_event_checkin_state(p_event_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  target_event public.club_events;
  setting public.event_checkin_settings;
  actor_membership_id uuid;
  attendance public.event_attendances;
  active_session public.event_checkin_sessions;
begin
  select * into target_event
  from public.club_events
  where id = p_event_id and event_status in ('published', 'cancelled', 'completed');
  if not found then
    raise exception using errcode = 'P0002', message = 'event_not_available';
  end if;
  actor_membership_id := public.current_checkin_membership_id(target_event.club_id);
  if actor_membership_id is null then
    raise exception using errcode = '42501', message = 'active_membership_required';
  end if;

  select * into setting
  from public.event_checkin_settings
  where event_id = target_event.id and club_id = target_event.club_id;
  select * into attendance
  from public.event_attendances
  where event_id = target_event.id
    and membership_id = actor_membership_id
    and attendance_status = 'active';
  select * into active_session
  from public.event_checkin_sessions
  where event_id = target_event.id
    and session_status = 'active'
    and expires_at > now()
  order by created_at desc
  limit 1;

  return jsonb_build_object(
    'event_id', target_event.id,
    'title', target_event.title,
    'location', target_event.location,
    'starts_at', target_event.starts_at,
    'ends_at', target_event.ends_at,
    'event_status', target_event.event_status,
    'configured', setting.event_id is not null,
    'window_open', setting.event_id is not null
      and now() >= setting.opens_at and now() <= setting.closes_at,
    'opens_at', setting.opens_at,
    'closes_at', setting.closes_at,
    'gps_enabled', coalesce(setting.gps_enabled, false),
    'qr_enabled', coalesce(setting.qr_enabled, false),
    'qr_session_open', active_session.id is not null,
    'checked_in', attendance.id is not null,
    'attendance_id', attendance.id,
    'checkin_method', attendance.checkin_method,
    'checked_in_at', attendance.checked_in_at
  );
end;
$$;

create or replace function public.get_event_checkin_overview(p_club_id uuid, p_event_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  actor_id uuid := public.current_app_account_id();
  result jsonb;
begin
  if actor_id is null or not public.current_can_manage_event_checkin(p_club_id) then
    raise exception using errcode = '42501', message = 'attendance_manage_required';
  end if;

  select jsonb_build_object(
    'event', jsonb_build_object(
      'id', event.id,
      'title', event.title,
      'location', event.location,
      'starts_at', event.starts_at,
      'ends_at', event.ends_at,
      'status', event.event_status,
      'counts_for_attendance', event.counts_for_attendance
    ),
    'settings', case when setting.event_id is null then null else jsonb_build_object(
      'gps_enabled', setting.gps_enabled,
      'qr_enabled', setting.qr_enabled,
      'latitude', setting.latitude,
      'longitude', setting.longitude,
      'radius_meters', setting.radius_meters,
      'max_accuracy_meters', setting.max_accuracy_meters,
      'opens_at', setting.opens_at,
      'closes_at', setting.closes_at,
      'qr_rotation_seconds', setting.qr_rotation_seconds,
      'window_open', now() between setting.opens_at and setting.closes_at
    ) end,
    'active_session', (
      select jsonb_build_object(
        'id', session.id,
        'opens_at', session.opens_at,
        'expires_at', session.expires_at,
        'expired', session.expires_at <= now()
      )
      from public.event_checkin_sessions as session
      where session.event_id = event.id and session.session_status = 'active'
      order by session.created_at desc limit 1
    ),
    'summary', jsonb_build_object(
      'active_members', (
        select count(*)
        from public.club_memberships as membership
        where membership.club_id = p_club_id and membership.membership_status = 'active'
      ),
      'checked_in', (
        select count(*)
        from public.event_attendances as attendance
        where attendance.event_id = event.id
          and attendance.club_id = p_club_id
          and attendance.attendance_status = 'active'
      )
    ),
    'members', coalesce((
      select jsonb_agg(jsonb_build_object(
        'membership_id', membership.id,
        'membership_number', membership.membership_number,
        'display_name', person.canonical_name,
        'checked_in', attendance.id is not null,
        'attendance_id', attendance.id,
        'checked_in_at', attendance.checked_in_at,
        'checkin_method', attendance.checkin_method
      ) order by person.canonical_name, membership.id)
      from public.club_memberships as membership
      join public.people as person on person.id = membership.person_id
      left join public.event_attendances as attendance
        on attendance.event_id = event.id
       and attendance.membership_id = membership.id
       and attendance.attendance_status = 'active'
      where membership.club_id = p_club_id and membership.membership_status = 'active'
    ), '[]'::jsonb),
    'attendance_history', coalesce((
      select jsonb_agg(jsonb_build_object(
        'attendance_id', attendance.id,
        'membership_id', attendance.membership_id,
        'display_name', person.canonical_name,
        'status', attendance.attendance_status,
        'checkin_method', attendance.checkin_method,
        'checked_in_at', attendance.checked_in_at,
        'checkin_note', attendance.checkin_note,
        'location_accuracy_meters', attendance.location_accuracy_meters,
        'distance_meters', attendance.distance_meters,
        'revoked_at', attendance.revoked_at,
        'revoke_reason', attendance.revoke_reason
      ) order by attendance.checked_in_at desc, attendance.id desc)
      from public.event_attendances as attendance
      join public.club_memberships as membership on membership.id = attendance.membership_id
      join public.people as person on person.id = membership.person_id
      where attendance.event_id = event.id and attendance.club_id = p_club_id
    ), '[]'::jsonb),
    'recent_attempts', coalesce((
      select jsonb_agg(attempt_row.item order by attempt_row.created_at desc, attempt_row.id desc)
      from (
        select attempt.id, attempt.created_at, jsonb_build_object(
          'id', attempt.id,
          'display_name', person.canonical_name,
          'method', attempt.method,
          'result_code', attempt.result_code,
          'location_accuracy_meters', attempt.location_accuracy_meters,
          'distance_meters', attempt.distance_meters,
          'created_at', attempt.created_at
        ) as item
        from public.event_checkin_attempts as attempt
        left join public.club_memberships as membership on membership.id = attempt.membership_id
        left join public.people as person on person.id = membership.person_id
        where attempt.event_id = event.id and attempt.club_id = p_club_id
        order by attempt.created_at desc, attempt.id desc
        limit 50
      ) as attempt_row
    ), '[]'::jsonb)
  ) into result
  from public.club_events as event
  left join public.event_checkin_settings as setting
    on setting.event_id = event.id and setting.club_id = event.club_id
  where event.id = p_event_id and event.club_id = p_club_id;

  if result is null then
    raise exception using errcode = 'P0002', message = 'event_not_available';
  end if;
  return result;
end;
$$;

create or replace function public.close_checkin_sessions_on_terminal_event()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if new.event_status in ('cancelled', 'completed')
     and old.event_status is distinct from new.event_status then
    update public.event_checkin_qr_credentials as credential
    set invalidated_at = coalesce(credential.invalidated_at, now())
    from public.event_checkin_sessions as session
    where session.id = credential.session_id
      and session.event_id = new.id
      and session.session_status = 'active'
      and credential.invalidated_at is null;

    update public.event_checkin_sessions
    set session_status = 'closed',
        closed_at = now(),
        close_reason = 'event_terminal',
        closed_by_app_account_id = new.updated_by_app_account_id
    where event_id = new.id and session_status = 'active';
  end if;
  return new;
end;
$$;

create or replace function public.get_my_attendance_receipt(p_attendance_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  result jsonb;
begin
  select jsonb_build_object(
    'attendance_id', attendance.id,
    'event_id', event.id,
    'title', event.title,
    'location', event.location,
    'starts_at', event.starts_at,
    'checked_in_at', attendance.checked_in_at,
    'checkin_method', attendance.checkin_method
  ) into result
  from public.event_attendances as attendance
  join public.club_events as event
    on event.id = attendance.event_id and event.club_id = attendance.club_id
  where attendance.id = p_attendance_id
    and attendance.attendance_status = 'active'
    and attendance.membership_id = public.current_checkin_membership_id(attendance.club_id);

  if result is null then
    raise exception using errcode = 'P0002', message = 'attendance_not_available';
  end if;
  return result;
end;
$$;

create or replace function public.record_client_checkin_failure(
  p_event_id uuid,
  p_method text,
  p_result_code text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  actor_id uuid := public.current_app_account_id();
  event public.club_events;
  setting public.event_checkin_settings;
  membership_id uuid;
begin
  if p_method not in ('gps', 'qr') or p_result_code not in (
    'location_permission_denied', 'location_timeout', 'location_unavailable',
    'camera_permission_denied', 'camera_unsupported', 'camera_error'
  ) then
    raise exception using errcode = '22023', message = 'invalid_client_checkin_failure';
  end if;

  select * into event from public.club_events where id = p_event_id;
  if actor_id is null or event.id is null then
    raise exception using errcode = '42501', message = 'checkin_not_eligible';
  end if;
  membership_id := public.current_checkin_membership_id(event.club_id);
  if membership_id is null then
    raise exception using errcode = '42501', message = 'checkin_not_eligible';
  end if;
  select * into setting from public.event_checkin_settings
  where event_id = event.id and club_id = event.club_id;
  if setting.event_id is null
     or (p_method = 'gps' and not setting.gps_enabled)
     or (p_method = 'qr' and not setting.qr_enabled) then
    raise exception using errcode = '42501', message = 'checkin_method_not_available';
  end if;
  if (
    select count(*) from public.event_checkin_attempts as attempt
    where attempt.actor_app_account_id = actor_id
      and attempt.event_id = event.id
      and attempt.created_at > now() - interval '1 minute'
  ) >= 20 then return; end if;

  perform public.record_event_checkin_attempt(
    event.club_id, event.id, membership_id, actor_id,
    p_method, p_result_code, null, null,
    jsonb_build_object('source', 'member_client')
  );
end;
$$;

create or replace function public.protect_event_attendance_update()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if old.id is distinct from new.id
     or old.club_id is distinct from new.club_id
     or old.event_id is distinct from new.event_id
     or old.membership_id is distinct from new.membership_id
     or old.checkin_session_id is distinct from new.checkin_session_id
     or old.checkin_method is distinct from new.checkin_method
     or old.checked_in_at is distinct from new.checked_in_at
     or old.checked_in_by_app_account_id is distinct from new.checked_in_by_app_account_id
     or old.checkin_note is distinct from new.checkin_note
     or old.location_accuracy_meters is distinct from new.location_accuracy_meters
     or old.distance_meters is distinct from new.distance_meters
     or old.created_at is distinct from new.created_at then
    raise exception using errcode = '23514', message = 'event_attendance_immutable_field';
  end if;
  if old.attendance_status = 'revoked' and new.attendance_status <> 'revoked' then
    raise exception using errcode = '23514', message = 'revoked_attendance_cannot_restore';
  end if;
  new.updated_at := now();
  if new.attendance_status = 'revoked' then
    new.revoked_at := coalesce(old.revoked_at, new.revoked_at, now());
    new.revoke_reason := btrim(coalesce(new.revoke_reason, ''));
    if new.revoked_by_app_account_id is null or new.revoke_reason = '' then
      raise exception using errcode = '23514', message = 'attendance_revoke_metadata_required';
    end if;
  end if;
  return new;
end;
$$;

create or replace function public.prevent_event_checkin_v2_hard_delete()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  raise exception using errcode = '42501', message = 'event_checkin_hard_delete_forbidden';
end;
$$;

create trigger event_checkin_settings_prevent_delete
before delete on public.event_checkin_settings
for each row execute function public.prevent_event_checkin_v2_hard_delete();
create trigger event_checkin_qr_credentials_prevent_delete
before delete on public.event_checkin_qr_credentials
for each row execute function public.prevent_event_checkin_v2_hard_delete();
create trigger event_checkin_attempts_prevent_delete
before delete on public.event_checkin_attempts
for each row execute function public.prevent_event_checkin_v2_hard_delete();
create trigger event_checkin_attempts_prevent_update
before update on public.event_checkin_attempts
for each row execute function public.prevent_event_checkin_v2_hard_delete();

alter table public.event_checkin_settings enable row level security;
alter table public.event_checkin_qr_credentials enable row level security;
alter table public.event_checkin_attempts enable row level security;

revoke all on table public.event_checkin_settings,
  public.event_checkin_qr_credentials,
  public.event_checkin_attempts
  from public, anon, authenticated;
grant select, insert, update on table public.event_checkin_settings,
  public.event_checkin_qr_credentials,
  public.event_checkin_attempts
  to service_role;

revoke execute on function public.open_event_checkin(uuid, uuid, integer) from authenticated;
revoke execute on function public.rotate_event_checkin_token(uuid, uuid, integer) from authenticated;
revoke execute on function public.check_in_to_event(text) from authenticated;

revoke all on function public.current_checkin_membership_id(uuid) from public, anon, authenticated;
revoke all on function public.event_distance_meters(numeric, numeric, numeric, numeric) from public, anon, authenticated;
revoke all on function public.record_event_checkin_attempt(uuid, uuid, uuid, uuid, text, text, numeric, numeric, jsonb) from public, anon, authenticated;
revoke all on function public.prevent_event_checkin_v2_hard_delete() from public, anon, authenticated;
revoke all on function public.configure_event_checkin(uuid, uuid, boolean, boolean, numeric, numeric, integer, integer, timestamptz, timestamptz, integer) from public, anon;
revoke all on function public.start_event_checkin_session(uuid, uuid) from public, anon;
revoke all on function public.issue_event_checkin_qr(uuid, uuid) from public, anon;
revoke all on function public.preview_event_qr_checkin(text) from public, anon;
revoke all on function public.confirm_event_qr_checkin(text) from public, anon;
revoke all on function public.check_in_by_gps(uuid, numeric, numeric, numeric) from public, anon;
revoke all on function public.get_my_event_checkin_state(uuid) from public, anon;
revoke all on function public.get_my_attendance_receipt(uuid) from public, anon;
revoke all on function public.record_client_checkin_failure(uuid, text, text) from public, anon;
revoke all on function public.get_event_checkin_overview(uuid, uuid) from public, anon;

grant execute on function public.configure_event_checkin(uuid, uuid, boolean, boolean, numeric, numeric, integer, integer, timestamptz, timestamptz, integer) to authenticated;
grant execute on function public.start_event_checkin_session(uuid, uuid) to authenticated;
grant execute on function public.issue_event_checkin_qr(uuid, uuid) to authenticated;
grant execute on function public.preview_event_qr_checkin(text) to authenticated;
grant execute on function public.confirm_event_qr_checkin(text) to authenticated;
grant execute on function public.check_in_by_gps(uuid, numeric, numeric, numeric) to authenticated;
grant execute on function public.get_my_event_checkin_state(uuid) to authenticated;
grant execute on function public.get_my_attendance_receipt(uuid) to authenticated;
grant execute on function public.record_client_checkin_failure(uuid, text, text) to authenticated;
grant execute on function public.get_event_checkin_overview(uuid, uuid) to authenticated;

commit;
